'use client'
import { useState, useEffect, useCallback } from 'react'
import { DECOS } from '@/config/decorations'

const EDIT_KEY = 'hstar_edit'
const decoKey = (id: string) => `hstar_deco_${id}`
const LS_CUSTOM = 'hstar_custom_decos'

export function EditBar() {
  const [open, setOpen] = useState(false)
  const [isEdit, setIsEdit] = useState(false)
  const [overrides, setOverrides] = useState<Record<string, { left: number; top: number; width: number } | null>>({})
  const [copied, setCopied] = useState(false)
  const [mounted, setMounted] = useState(false)
  const [tab, setTab] = useState<'controls' | 'images'>('controls')
  const [images, setImages] = useState<string[]>([])
  const [uploading, setUploading] = useState(false)

  const refreshOverrides = useCallback(() => {
    const result: Record<string, { left: number; top: number; width: number } | null> = {}
    for (const id of Object.keys(DECOS)) {
      try {
        const v = localStorage.getItem(decoKey(id))
        result[id] = v ? JSON.parse(v) : null
      } catch { result[id] = null }
    }
    setOverrides(result)
  }, [])

  const fetchImages = useCallback(async () => {
    try {
      const res = await fetch('/api/editor/images')
      const data = await res.json()
      setImages(data)
    } catch {}
  }, [])

  useEffect(() => {
    setMounted(true)
    try {
      setIsEdit(localStorage.getItem(EDIT_KEY) === '1')
      refreshOverrides()
    } catch {}
    window.addEventListener('hstar-pos', refreshOverrides)
    return () => window.removeEventListener('hstar-pos', refreshOverrides)
  }, [refreshOverrides])

  useEffect(() => {
    if (open) fetchImages()
  }, [open, fetchImages])

  useEffect(() => {
    if (tab === 'images') fetchImages()
  }, [tab, fetchImages])

  // Don't render until client is mounted (avoids hydration mismatch)
  if (!mounted) return null

  function toggleEdit() {
    const next = !isEdit
    try { localStorage.setItem(EDIT_KEY, next ? '1' : '0') } catch {}
    setIsEdit(next)
    window.dispatchEvent(new Event('hstar-edit'))
  }

  function addImageToDeco(src: string) {
    try {
      const existing = JSON.parse(localStorage.getItem(LS_CUSTOM) || '[]')
      const newDeco = {
        id: Date.now().toString(),
        src,
        label: src.split('/').pop()?.replace(/\.[^.]+$/, '') ?? 'image',
        left: Math.round(window.innerWidth / 2 - 100),
        top: Math.round(window.scrollY + window.innerHeight / 2 - 100),
        width: 200,
      }
      localStorage.setItem(LS_CUSTOM, JSON.stringify([...existing, newDeco]))
      window.dispatchEvent(new Event('hstar-custom'))
    } catch {}
  }

  async function handleUpload(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0]
    if (!file) return
    setUploading(true)
    try {
      const fd = new FormData()
      fd.append('file', file)
      const res = await fetch('/api/editor/upload', { method: 'POST', body: fd })
      const data = await res.json()
      if (data.path) {
        await fetchImages()
        addImageToDeco(data.path)
      }
    } catch {}
    setUploading(false)
    e.target.value = ''
  }

  function exportConfig() {
    const vp = `${window.innerWidth}x${window.innerHeight}`
    const lines: string[] = [
      `// Generated by Deco Editor — viewport ${vp}`,
      `// Paste these entries into config/decorations.ts → DECOS`,
      '',
    ]
    for (const [id, cfg] of Object.entries(DECOS)) {
      const saved = overrides[id] ?? null
      const styleObj = saved ? { left: saved.left, top: saved.top, width: saved.width } : cfg.style
      const styleStr = JSON.stringify(styleObj)
        .replace(/"([^"]+)":/g, '$1:')
        .replace(/,/g, ', ')
        .replace(/{/, '{ ')
        .replace(/}/, ' }')
      lines.push(`  '${id}': {`)
      lines.push(`    src: '${cfg.src}',`)
      lines.push(`    label: '${cfg.label}',`)
      lines.push(`    style: ${styleStr} as CSSProperties,`)
      lines.push(`  },`)
    }

    // Include custom decos in export
    try {
      const customDecos = JSON.parse(localStorage.getItem(LS_CUSTOM) || '[]')
      if (customDecos.length > 0) {
        lines.push('')
        lines.push('// Custom decos (add these to DECOS in config/decorations.ts and copy src files if needed)')
        for (const d of customDecos) {
          const styleStr = `{ left: ${d.left}, top: ${d.top}, width: ${d.width} }`
          lines.push(`  '${d.id}': {`)
          lines.push(`    src: '${d.src}',`)
          lines.push(`    label: '${d.label}',`)
          lines.push(`    style: ${styleStr} as CSSProperties,`)
          lines.push(`  },`)
        }
      }
    } catch {}

    navigator.clipboard.writeText(lines.join('\n')).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }).catch(() => alert(lines.join('\n')))
  }

  function resetAll() {
    if (!confirm('Reset all deco overrides?')) return
    Object.keys(DECOS).forEach(id => { try { localStorage.removeItem(decoKey(id)) } catch {} })
    try { localStorage.removeItem('hstar_hidden_decos') } catch {}
    try { localStorage.removeItem(LS_CUSTOM) } catch {}
    refreshOverrides()
    window.location.reload()
  }

  const hasAny = Object.values(overrides).some(v => v !== null)
  const overrideCount = Object.values(overrides).filter(v => v !== null).length

  return (
    <div
      style={{
        position: 'fixed',
        bottom: 24,
        right: 24,
        zIndex: 99999,
        fontFamily: 'monospace',
        pointerEvents: 'auto',
      }}
    >
      {open && (
        <div style={{
          background: '#0f172a',
          border: '2px solid #3b82f6',
          borderRadius: 12,
          padding: 16,
          marginBottom: 10,
          width: 310,
          boxShadow: '0 8px 40px rgba(0,0,0,0.8)',
          pointerEvents: 'auto',
        }}>
          <p style={{ color: '#94a3b8', fontSize: 11, fontWeight: 800, letterSpacing: 1.5, marginBottom: 10, textTransform: 'uppercase' }}>
            🎨 Deco Editor
          </p>

          {/* Tabs */}
          <div style={{ display: 'flex', gap: 4, marginBottom: 12 }}>
            <button
              type="button"
              onClick={() => setTab('controls')}
              style={{
                flex: 1, padding: '6px 0', borderRadius: 6, cursor: 'pointer',
                fontSize: 11, fontWeight: 800, fontFamily: 'monospace',
                background: tab === 'controls' ? '#1e3a8a' : '#1e293b',
                color: tab === 'controls' ? '#93c5fd' : '#64748b',
                border: `2px solid ${tab === 'controls' ? '#3b82f6' : '#334155'}`,
              }}
            >
              Controls
            </button>
            <button
              type="button"
              onClick={() => setTab('images')}
              style={{
                flex: 1, padding: '6px 0', borderRadius: 6, cursor: 'pointer',
                fontSize: 11, fontWeight: 800, fontFamily: 'monospace',
                background: tab === 'images' ? '#1e3a8a' : '#1e293b',
                color: tab === 'images' ? '#93c5fd' : '#64748b',
                border: `2px solid ${tab === 'images' ? '#3b82f6' : '#334155'}`,
              }}
            >
              Images ({images.length})
            </button>
          </div>

          {tab === 'controls' && (
            <>
              <button
                type="button"
                onClick={toggleEdit}
                style={{
                  display: 'block', width: '100%',
                  padding: '10px 14px', marginBottom: 8,
                  borderRadius: 8, cursor: 'pointer',
                  fontSize: 13, fontWeight: 800, textAlign: 'left',
                  fontFamily: 'monospace',
                  background: isEdit ? '#1e3a8a' : '#1e293b',
                  color: isEdit ? '#93c5fd' : '#64748b',
                  border: `2px solid ${isEdit ? '#3b82f6' : '#334155'}`,
                  pointerEvents: 'auto',
                }}
              >
                {isEdit ? '⦿  Edit Mode ON — drag images' : '○  Edit Mode OFF'}
              </button>

              <button
                type="button"
                onClick={exportConfig}
                style={{
                  display: 'block', width: '100%',
                  padding: '10px 14px', marginBottom: 8,
                  borderRadius: 8, cursor: 'pointer',
                  fontSize: 13, fontWeight: 800, textAlign: 'left',
                  fontFamily: 'monospace',
                  background: '#1e293b',
                  color: hasAny ? '#fbbf24' : '#64748b',
                  border: `2px solid ${hasAny ? '#f59e0b' : '#334155'}`,
                  pointerEvents: 'auto',
                }}
              >
                {copied ? '✓  Copied to clipboard!' : `↑  Copy Config${overrideCount > 0 ? ` (${overrideCount} edited)` : ''}`}
              </button>

              <button
                type="button"
                onClick={resetAll}
                style={{
                  display: 'block', width: '100%',
                  padding: '10px 14px', marginBottom: 14,
                  borderRadius: 8, cursor: 'pointer',
                  fontSize: 13, fontWeight: 800, textAlign: 'left',
                  fontFamily: 'monospace',
                  background: '#1e293b',
                  color: hasAny ? '#f87171' : '#475569',
                  border: '2px solid #334155',
                  pointerEvents: 'auto',
                }}
              >
                ✕  Reset All
              </button>

              <div style={{ borderTop: '1px solid #1e293b', paddingTop: 10 }}>
                {Object.entries(DECOS).map(([id, cfg]) => (
                  <div key={id} style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 5 }}>
                    <span style={{
                      width: 8, height: 8, borderRadius: '50%', flexShrink: 0,
                      background: overrides[id] ? '#22c55e' : '#334155',
                      display: 'inline-block',
                    }} />
                    <span style={{ fontSize: 11, color: overrides[id] ? '#86efac' : '#475569', flex: 1 }}>
                      {cfg.label}
                    </span>
                    {overrides[id] && (
                      <span style={{ fontSize: 10, color: '#64748b' }}>
                        {overrides[id]!.width}px
                      </span>
                    )}
                  </div>
                ))}
              </div>
            </>
          )}

          {tab === 'images' && (
            <div>
              {/* Upload button */}
              <label style={{
                display: 'block', width: '100%',
                padding: '10px 14px', marginBottom: 10,
                borderRadius: 8, cursor: uploading ? 'wait' : 'pointer',
                fontSize: 13, fontWeight: 800, textAlign: 'center',
                fontFamily: 'monospace',
                background: '#1e293b',
                color: uploading ? '#64748b' : '#fbbf24',
                border: '2px solid #f59e0b',
                pointerEvents: 'auto',
                boxSizing: 'border-box',
              }}>
                {uploading ? '⏳ Uploading...' : '↑ Upload Image'}
                <input
                  type="file"
                  accept="image/*"
                  onChange={handleUpload}
                  disabled={uploading}
                  style={{ display: 'none' }}
                />
              </label>

              {/* Image grid */}
              <div style={{
                maxHeight: 240,
                overflowY: 'auto',
                display: 'grid',
                gridTemplateColumns: 'repeat(4, 1fr)',
                gap: 6,
              }}>
                {images.length === 0 && (
                  <div style={{ gridColumn: 'span 4', color: '#475569', fontSize: 11, textAlign: 'center', padding: '16px 0' }}>
                    No images found
                  </div>
                )}
                {images.map(src => (
                  <button
                    key={src}
                    type="button"
                    title={src.split('/').pop()}
                    onClick={() => addImageToDeco(src)}
                    style={{
                      padding: 0, border: '2px solid #334155', borderRadius: 6,
                      cursor: 'pointer', background: '#1e293b',
                      overflow: 'hidden', width: '100%', aspectRatio: '1',
                      display: 'flex', alignItems: 'center', justifyContent: 'center',
                    }}
                  >
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img
                      src={src}
                      alt=""
                      style={{ width: '100%', height: '100%', objectFit: 'contain' }}
                    />
                  </button>
                ))}
              </div>
            </div>
          )}
        </div>
      )}

      <button
        type="button"
        onClick={() => setOpen(prev => !prev)}
        style={{
          padding: '12px 20px',
          background: open ? '#2563eb' : '#FFE790',
          border: `3px solid ${open ? '#1d4ed8' : '#d4a800'}`,
          borderRadius: 9999,
          color: open ? '#fff' : '#000000',
          cursor: 'pointer',
          fontSize: 14,
          fontWeight: 900,
          letterSpacing: 0.5,
          display: 'flex',
          alignItems: 'center',
          gap: 8,
          boxShadow: '0 4px 24px rgba(0,0,0,0.5)',
          pointerEvents: 'auto',
          whiteSpace: 'nowrap',
          fontFamily: 'monospace',
        }}
      >
        ✏ {open ? 'Close' : 'Edit Images'}
        {hasAny && !open && (
          <span style={{
            background: '#ef4444',
            color: '#fff',
            borderRadius: 9999,
            fontSize: 11,
            fontWeight: 900,
            padding: '2px 7px',
          }}>
            {overrideCount}
          </span>
        )}
      </button>
    </div>
  )
}
